nat_gateway_zones:
  # private zone -> nat gateway zone の組み合わせ
  # dev 環境はコスト削減のため nat gateway を冗長化しない
  ap-northeast-1a: ap-northeast-1a
  ap-northeast-1c: ap-northeast-1a
alb:
  target_group:
    health_check:
      healthy_threshold: 2
      unhealthy_threshold: 2
      interval: 30
      timeout: 10
ecs_capacity_providers:
  fargate:
    base: 0
    weight: 0
  fargate_spot:
    base: 1
    weight: 1
rds:
  database_name: example
  master_username: root
